---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install:
  - sudo apt-get -yq remove --purge mysql-server* mysql-client*

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - "ansible-playbook tests/test.yml -i tests/inventory --connection=local"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/