---
language: python
python: "2.7"
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install:
  # remove mysql
  - "sudo apt-get remove --purge mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5"
  - "sudo apt-get autoremove --purge"
  - "sudo rm -rf /var/lib/mysql"
  - "echo never | sudo tee /sys/kernel/mm/transparent_hugepage/enabled"
  - "echo never | sudo tee /sys/kernel/mm/transparent_hugepage/defrag"

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - "ansible-playbook tests/test.yml -i tests/inventory --connection=local"

#after_script:
#  - "sudo tail -n 1000 /var/log/syslog"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/